name: Check Format
on:
  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/clang-format.yml'
jobs:
  formatting-check:
    name: Run clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.12.0
      with:
        clang-format-version: '18'
        include-regex: '^\.\/(Tests|Sources)\/.*\.(c|cpp|h|m)$'
